//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kent.Boogaart.Converters.UnitTests.Expressions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TokenizerTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenizerTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kent.Boogaart.Converters.UnitTests.Expressions.TokenizerTestResources", typeof(TokenizerTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\&apos;\&quot;\\\0\a\b\f\n\r\t\v&quot;.
        /// </summary>
        internal static string ReadNextToken_ShouldHandleAllEscapeSequences {
            get {
                return ResourceManager.GetString("ReadNextToken_ShouldHandleAllEscapeSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1+2 * (15/ {0}) + ((int) {1} *{2}) &lt;&lt;3 == &quot;something&quot; +&quot;something else&quot;.
        /// </summary>
        internal static string ReadNextToken_ShouldHandleComplexExpressions {
            get {
                return ResourceManager.GetString("ReadNextToken_ShouldHandleComplexExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;one&quot; &quot;two&quot; &quot;three \&quot; four&quot;.
        /// </summary>
        internal static string ReadNextToken_ShouldReturnStringForStrings {
            get {
                return ResourceManager.GetString("ReadNextToken_ShouldReturnStringForStrings", resourceCulture);
            }
        }
    }
}
