// <auto-generated/>
using System;
using System.Reflection;
using System.Resources;

[assembly: AssemblyVersionAttribute("1.3.1.0")]
[assembly: AssemblyFileVersionAttribute("1.3.1.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyCompanyAttribute("Kent Boogaart")]
[assembly: AssemblyProductAttribute("WPF Converters")]
[assembly: AssemblyCopyrightAttribute("© Copyright. Kent Boogaart.")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: CLSCompliantAttribute(true)]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersionAttribute("1.3.1")]
